[package]
name = "genzh-room"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
genzh-domain.workspace = true
genzh-community.workspace = true
genzh-graph.workspace = true
genzh-infrastructure.workspace = true
genzh-media-core.workspace = true
serde.workspace = true
sqlx.workspace = true
uuid.workspace = true
chrono.workspace = true
tracing.workspace = true
