-- Initial control-plane schema.
--
-- Conventions used throughout:
--   * UUID primary keys, generated by the application so an aggregate has its
--     identity before it is persisted.
--   * TIMESTAMPTZ everywhere; the database stores UTC and the domain type is
--     DateTime<Utc>. There are no naive timestamps anywhere in the system.
--   * ON DELETE CASCADE where a child row is meaningless without its parent
--     (a room without a community, a reaction without a message), and
--     RESTRICT where deletion should be a deliberate act.

-- ─────────────────────────────── enums ───────────────────────────────

-- A room's purpose. Voice/Video/Activity rooms carry media; Text does not.
CREATE TYPE room_type AS ENUM ('text', 'voice', 'video', 'activity');

CREATE TYPE friendship_status AS ENUM ('pending', 'accepted', 'declined');

-- Room-level permission overrides either grant or revoke.
CREATE TYPE permission_effect AS ENUM ('allow', 'deny');

-- ────────────────────────────── identity ─────────────────────────────

CREATE TABLE users (
    id            UUID PRIMARY KEY,
    -- Stored lower-cased by the domain, so uniqueness is case-insensitive
    -- without needing citext or a functional index.
    handle        TEXT        NOT NULL,
    email         TEXT        NOT NULL,
    -- Argon2id PHC string. Never a plaintext password, never a bare digest.
    password_hash TEXT        NOT NULL,
    is_active     BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT users_handle_key UNIQUE (handle),
    CONSTRAINT users_email_key  UNIQUE (email)
);

CREATE TABLE profiles (
    user_id       UUID PRIMARY KEY REFERENCES users (id) ON DELETE CASCADE,
    display_name  TEXT        NOT NULL,
    bio           TEXT,
    avatar_url    TEXT,
    -- Key of an animated avatar effect from the creator marketplace. Kept as a
    -- plain key rather than a foreign key so the marketplace can ship
    -- independently of this schema.
    avatar_effect TEXT,
    accent_color  TEXT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- One row per refresh token. Storing a hash rather than the token means a
-- database leak does not hand out live sessions.
CREATE TABLE sessions (
    id                  UUID PRIMARY KEY,
    user_id             UUID        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    refresh_token_hash  TEXT        NOT NULL,
    user_agent          TEXT,
    ip_address          TEXT,
    expires_at          TIMESTAMPTZ NOT NULL,
    revoked_at          TIMESTAMPTZ,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT sessions_refresh_token_hash_key UNIQUE (refresh_token_hash)
);

CREATE INDEX sessions_user_id_idx ON sessions (user_id);
-- Supports the periodic sweep of expired rows.
CREATE INDEX sessions_expires_at_idx ON sessions (expires_at);

-- ───────────────────────────── communities ───────────────────────────

CREATE TABLE communities (
    id          UUID PRIMARY KEY,
    name        TEXT        NOT NULL,
    description TEXT,
    icon_url    TEXT,
    -- RESTRICT: deleting an account must not silently destroy communities it
    -- owns. Ownership has to be transferred first.
    owner_id    UUID        NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX communities_owner_id_idx ON communities (owner_id);

CREATE TABLE community_members (
    community_id UUID        NOT NULL REFERENCES communities (id) ON DELETE CASCADE,
    user_id      UUID        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    nickname     TEXT,
    joined_at    TIMESTAMPTZ NOT NULL DEFAULT now(),

    PRIMARY KEY (community_id, user_id)
);

-- "Which communities am I in?" is on the hot path of every client boot.
CREATE INDEX community_members_user_id_idx ON community_members (user_id);

CREATE TABLE roles (
    id           UUID PRIMARY KEY,
    community_id UUID        NOT NULL REFERENCES communities (id) ON DELETE CASCADE,
    name         TEXT        NOT NULL,
    color        TEXT,
    -- Higher position wins when roles disagree, and gates who may edit whom.
    position     INTEGER     NOT NULL DEFAULT 0,
    -- The implicit @everyone role. Exactly one per community, undeletable.
    is_default   BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT roles_community_id_name_key UNIQUE (community_id, name)
);

CREATE INDEX roles_community_id_idx ON roles (community_id);
CREATE UNIQUE INDEX roles_one_default_per_community_idx
    ON roles (community_id) WHERE is_default;

-- The permission catalogue. Seeded by a later migration from
-- social_domain::Permission::ALL; a test asserts the two never drift.
CREATE TABLE permissions (
    key         TEXT PRIMARY KEY,
    description TEXT NOT NULL
);

CREATE TABLE role_permissions (
    role_id        UUID NOT NULL REFERENCES roles (id) ON DELETE CASCADE,
    permission_key TEXT NOT NULL REFERENCES permissions (key) ON DELETE CASCADE,

    PRIMARY KEY (role_id, permission_key)
);

CREATE TABLE member_roles (
    community_id UUID        NOT NULL,
    user_id      UUID        NOT NULL,
    role_id      UUID        NOT NULL REFERENCES roles (id) ON DELETE CASCADE,
    assigned_at  TIMESTAMPTZ NOT NULL DEFAULT now(),

    PRIMARY KEY (community_id, user_id, role_id),
    -- Referencing the membership rather than the user is what makes it
    -- impossible to hold a role in a community you are not a member of.
    FOREIGN KEY (community_id, user_id)
        REFERENCES community_members (community_id, user_id) ON DELETE CASCADE
);

CREATE INDEX member_roles_role_id_idx ON member_roles (role_id);

-- ──────────────────────────────── rooms ──────────────────────────────

CREATE TABLE rooms (
    id               UUID PRIMARY KEY,
    community_id     UUID        NOT NULL REFERENCES communities (id) ON DELETE CASCADE,
    name             TEXT        NOT NULL,
    topic            TEXT,
    room_type        room_type   NOT NULL,
    position         INTEGER     NOT NULL DEFAULT 0,
    -- NULL means "use the server default".
    max_participants INTEGER,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT rooms_max_participants_positive
        CHECK (max_participants IS NULL OR max_participants > 0)
);

CREATE INDEX rooms_community_id_idx ON rooms (community_id, position);

-- Per-room overrides layered on top of a role's community-wide grants.
CREATE TABLE room_permissions (
    room_id        UUID              NOT NULL REFERENCES rooms (id) ON DELETE CASCADE,
    role_id        UUID              NOT NULL REFERENCES roles (id) ON DELETE CASCADE,
    permission_key TEXT              NOT NULL REFERENCES permissions (key) ON DELETE CASCADE,
    effect         permission_effect NOT NULL,

    PRIMARY KEY (room_id, role_id, permission_key)
);

CREATE INDEX room_permissions_room_id_idx ON room_permissions (room_id);

-- ─────────────────────────────── messages ────────────────────────────

CREATE TABLE messages (
    id         UUID PRIMARY KEY,
    room_id    UUID        NOT NULL REFERENCES rooms (id) ON DELETE CASCADE,
    author_id  UUID        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    content    TEXT        NOT NULL,
    edited_at  TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- History is always read newest-first within one room; the id breaks ties for
-- messages written in the same microsecond so keyset pagination is stable.
CREATE INDEX messages_room_id_created_at_idx
    ON messages (room_id, created_at DESC, id DESC);

CREATE TABLE message_reactions (
    message_id UUID        NOT NULL REFERENCES messages (id) ON DELETE CASCADE,
    user_id    UUID        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    reaction   TEXT        NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- One user, one reaction, once.
    PRIMARY KEY (message_id, user_id, reaction)
);

CREATE INDEX message_reactions_message_id_idx ON message_reactions (message_id);

-- ────────────────────────────── social graph ─────────────────────────

CREATE TABLE friendships (
    requester_id UUID              NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    addressee_id UUID              NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    status       friendship_status NOT NULL DEFAULT 'pending',
    created_at   TIMESTAMPTZ       NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ       NOT NULL DEFAULT now(),

    PRIMARY KEY (requester_id, addressee_id),
    CONSTRAINT friendships_not_self CHECK (requester_id <> addressee_id)
);

-- A friendship is an unordered pair, but the row records who asked. This index
-- is what stops A→B and B→A both existing.
CREATE UNIQUE INDEX friendships_unordered_pair_idx ON friendships (
    LEAST(requester_id, addressee_id),
    GREATEST(requester_id, addressee_id)
);

CREATE INDEX friendships_addressee_idx ON friendships (addressee_id, status);

-- Blocks are one-directional on purpose: A blocking B says nothing about
-- whether B blocks A.
CREATE TABLE blocks (
    blocker_id UUID        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    blocked_id UUID        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    PRIMARY KEY (blocker_id, blocked_id),
    CONSTRAINT blocks_not_self CHECK (blocker_id <> blocked_id)
);

CREATE INDEX blocks_blocked_id_idx ON blocks (blocked_id);
